services:
  # 1. KDMS 데이터베이스 (TimescaleDB HA - PG16)
  kdms_db:
    image: timescale/timescaledb-ha:pg16
    container_name: kdms_timescaledb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-roid}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-kdms_db}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/kdms_db:/var/lib/postgresql/data
      - ./tdms_core/p1_shared/p1_shared/db/kdms_origin:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - tdms-net

  # 2. USDMS 데이터베이스 (TimescaleDB - PG16 - 서버 버전 일치)
  usdms_db:
    image: timescale/timescaledb@sha256:9e9f50161784dc57d3f547b89ded4af73553f9acb4677345ed05f45af7c7f664
    container_name: usdms_timescaledb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-roid}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: usdms_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/usdms_db:/var/lib/postgresql/data
      - ./tdms_core/p1_shared/p1_shared/db/usdms_origin:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - tdms-net

networks:
  tdms-net:
    driver: bridge
