# pg_hba.conf
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# 로컬 연결
local   all             all                                     trust

# IPv4 로컬 연결
host    all             all             127.0.0.1/32            md5

# Docker 네트워크 대역에서의 연결 허용 (개발 환경)
host    all             all             172.16.0.0/12           md5

# 로컬 네트워크 대역에서의 연결 허용 (운영 환경)
host    all             all             192.168.0.0/16          md5